
CREATE TABLE `country` (
  `id_country` int(11) NOT NULL,
  `name` varchar(50) DEFAULT NULL,
  `flag` varchar(4) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

--
-- Volcado de datos para la tabla `country`
--

INSERT INTO `country` (`id_country`, `name`, `flag`) VALUES
(1, 'Andorra', 'AD'),
(2, 'United Arab Emirates', 'AE'),
(3, 'Afghanistan', 'AF'),
(4, 'Antigua and Barbuda', 'AG'),
(5, 'Albania', 'AL'),
(6, 'Armenia', 'AM'),
(7, 'Angola', 'AO'),
(8, 'Antarctica', 'AQ'),
(9, 'Argentina', 'AR'),
(10, 'American Samoa', 'AS'),
(11, 'Austria', 'AT'),
(12, 'Australia', 'AU'),
(13, 'Aruba', 'AW'),
(14, 'Alland Islands', 'AX'),
(15, 'Azerbaijan', 'AZ'),
(16, 'Bosnia and Herzegovina', 'BA'),
(17, 'Barbados', 'BB'),
(18, 'Bangladesh', 'BD'),
(19, 'Belgium', 'BE'),
(20, 'Burkina Faso', 'BF'),
(21, 'Bulgaria', 'BG'),
(22, 'Bahrain', 'BH'),
(23, 'Burundi', 'BI'),
(24, 'Benin', 'BJ'),
(25, 'Saint Barthelemy', 'BL'),
(26, 'Bermuda', 'BM'),
(27, 'Brunei Darussalam', 'BN'),
(28, 'Bolivia', 'BO'),
(29, 'Brazil', 'BR'),
(30, 'Bahamas', 'BS'),
(31, 'Bhutan', 'BT'),
(32, 'Bouvet Island', 'BV'),
(33, 'Botswana', 'BW'),
(34, 'Belarus', 'BY'),
(35, 'Belize', 'BZ'),
(36, 'Canada', 'CA'),
(37, 'Cocos (Keeling) Islands', 'CC'),
(38, 'Congo, Republic of the', 'CD'),
(39, 'Central African Republic', 'CF'),
(40, 'Congo, Democratic Republic of the', 'CG'),
(41, 'Switzerland', 'CH'),
(42, 'Cote d\'Ivoire', 'CI'),
(43, 'Cook Islands', 'CK'),
(44, 'Chile', 'CL'),
(45, 'Cameroon', 'CM'),
(46, 'China', 'CN'),
(47, 'Colombia', 'CO'),
(48, 'Costa Rica', 'CR'),
(49, 'Cuba', 'CU'),
(50, 'Cape Verde', 'CV'),
(51, 'Curacao', 'CW'),
(52, 'Christmas Island', 'CX'),
(53, 'Cyprus', 'CY'),
(54, 'Czech Republic', 'CZ'),
(55, 'Germany', 'DE'),
(56, 'Djibouti', 'DJ'),
(57, 'Denmark', 'DK'),
(58, 'Dominica', 'DM'),
(59, 'Dominican Republic', 'DO'),
(60, 'Algeria', 'DZ'),
(61, 'Ecuador', 'EC'),
(62, 'Estonia', 'EE'),
(63, 'Egypt', 'EG'),
(64, 'Western Sahara', 'EH'),
(65, 'Eritrea', 'ER'),
(66, 'Spain', 'ES'),
(67, 'Ethiopia', 'ET'),
(68, 'Finland', 'FI'),
(69, 'Fiji', 'FJ'),
(70, 'Falkland Islands (Malvinas)', 'FK'),
(71, 'Micronesia, Federated States of', 'FM'),
(72, 'Faroe Islands', 'FO'),
(73, 'France', 'FR'),
(74, 'Gabon', 'GA'),
(75, 'United Kingdom', 'GB'),
(76, 'Grenada', 'GD'),
(77, 'Georgia', 'GE'),
(78, 'French Guiana', 'GF'),
(79, 'Guernsey', 'GG'),
(80, 'Ghana', 'GH'),
(81, 'Gibraltar', 'GI'),
(82, 'Greenland', 'GL'),
(83, 'Gambia', 'GM'),
(84, 'Guinea', 'GN'),
(85, 'Guadeloupe', 'GP'),
(86, 'Equatorial Guinea', 'GQ'),
(87, 'Greece', 'GR'),
(88, 'South Georgia and the South Sandwich Islands', 'GS'),
(89, 'Guatemala', 'GT'),
(90, 'Guam', 'GU'),
(91, 'Guinea-Bissau', 'GW'),
(92, 'Guyana', 'GY'),
(93, 'Hong Kong', 'HK'),
(94, 'Heard Island and McDonald Islands', 'HM'),
(95, 'Honduras', 'HN'),
(96, 'Croatia', 'HR'),
(97, 'Haiti', 'HT'),
(98, 'Hungary', 'HU'),
(99, 'Indonesia', 'ID'),
(100, 'Ireland', 'IE'),
(101, 'Israel', 'IL'),
(102, 'Isle of Man', 'IM'),
(103, 'India', 'IN'),
(104, 'British Indian Ocean Territory', 'IO'),
(105, 'Iraq', 'IQ'),
(106, 'Iran, Islamic Republic of', 'IR'),
(107, 'Iceland', 'IS'),
(108, 'Italy', 'IT'),
(109, 'Jersey', 'JE'),
(110, 'Jamaica', 'JM'),
(111, 'Jordan', 'JO'),
(112, 'Japan', 'JP'),
(113, 'Kenya', 'KE'),
(114, 'Kyrgyzstan', 'KG'),
(115, 'Cambodia', 'KH'),
(116, 'Kiribati', 'KI'),
(117, 'Comoros', 'KM'),
(118, 'Saint Kitts and Nevis', 'KN'),
(119, 'Korea, Democratic People\'s Republic of', 'KP'),
(120, 'Korea, Republic of', 'KR'),
(121, 'Kuwait', 'KW'),
(122, 'Cayman Islands', 'KY'),
(123, 'Kazakhstan', 'KZ'),
(124, 'Lao People\'s Democratic Republic', 'LA'),
(125, 'Lebanon', 'LB'),
(126, 'Saint Lucia', 'LC'),
(127, 'Liechtenstein', 'LI'),
(128, 'Sri Lanka', 'LK'),
(129, 'Liberia', 'LR'),
(130, 'Lesotho', 'LS'),
(131, 'Lithuania', 'LT'),
(132, 'Luxembourg', 'LU'),
(133, 'Latvia', 'LV'),
(134, 'Libya', 'LY'),
(135, 'Morocco', 'MA'),
(136, 'Monaco', 'MC'),
(137, 'Moldova, Republic of', 'MD'),
(138, 'Montenegro', 'ME'),
(139, 'Saint Martin (French part)', 'MF'),
(140, 'Madagascar', 'MG'),
(141, 'Marshall Islands', 'MH'),
(142, 'Macedonia, the Former Yugoslav Republic of', 'MK'),
(143, 'Mali', 'ML'),
(144, 'Myanmar', 'MM'),
(145, 'Mongolia', 'MN'),
(146, 'Macao', 'MO'),
(147, 'Northern Mariana Islands', 'MP'),
(148, 'Martinique', 'MQ'),
(149, 'Mauritania', 'MR'),
(150, 'Montserrat', 'MS'),
(151, 'Malta', 'MT'),
(152, 'Mauritius', 'MU'),
(153, 'Maldives', 'MV'),
(154, 'Malawi', 'MW'),
(155, 'Mexico', 'MX'),
(156, 'Malaysia', 'MY'),
(157, 'Mozambique', 'MZ'),
(158, 'Namibia', 'NA'),
(159, 'New Caledonia', 'NC'),
(160, 'Niger', 'NE'),
(161, 'Norfolk Island', 'NF'),
(162, 'Nigeria', 'NG'),
(163, 'Nicaragua', 'NI'),
(164, 'Netherlands', 'NL'),
(165, 'Norway', 'NO'),
(166, 'Nepal', 'NP'),
(167, 'Nauru', 'NR'),
(168, 'Niue', 'NU'),
(169, 'New Zealand', 'NZ'),
(170, 'Oman', 'OM'),
(171, 'Panama', 'PA'),
(172, 'Peru', 'PE'),
(173, 'French Polynesia', 'PF'),
(174, 'Papua New Guinea', 'PG'),
(175, 'Philippines', 'PH'),
(176, 'Pakistan', 'PK'),
(177, 'Poland', 'PL'),
(178, 'Saint Pierre and Miquelon', 'PM'),
(179, 'Pitcairn', 'PN'),
(180, 'Puerto Rico', 'PR'),
(181, 'Palestine, State of', 'PS'),
(182, 'Portugal', 'PT'),
(183, 'Palau', 'PW'),
(184, 'Paraguay', 'PY'),
(185, 'Qatar', 'QA'),
(186, 'Reunion', 'RE'),
(187, 'Romania', 'RO'),
(188, 'Serbia', 'RS'),
(189, 'Russian Federation', 'RU'),
(190, 'Rwanda', 'RW'),
(191, 'Saudi Arabia', 'SA'),
(192, 'Solomon Islands', 'SB'),
(193, 'Seychelles', 'SC'),
(194, 'Sudan', 'SD'),
(195, 'Sweden', 'SE'),
(196, 'Singapore', 'SG'),
(197, 'Saint Helena', 'SH'),
(198, 'Slovenia', 'SI'),
(199, 'Svalbard and Jan Mayen', 'SJ'),
(200, 'Slovakia', 'SK'),
(201, 'Sierra Leone', 'SL'),
(202, 'San Marino', 'SM'),
(203, 'Senegal', 'SN'),
(204, 'Somalia', 'SO'),
(205, 'Suriname', 'SR'),
(206, 'South Sudan', 'SS'),
(207, 'Sao Tome and Principe', 'ST'),
(208, 'El Salvador', 'SV'),
(209, 'Sint Maarten (Dutch part)', 'SX'),
(210, 'Syrian Arab Republic', 'SY'),
(211, 'Swaziland', 'SZ'),
(212, 'Turks and Caicos Islands', 'TC'),
(213, 'Chad', 'TD'),
(214, 'French Southern Territories', 'TF'),
(215, 'Togo', 'TG'),
(216, 'Thailand', 'TH'),
(217, 'Tajikistan', 'TJ'),
(218, 'Tokelau', 'TK'),
(219, 'Timor-Leste', 'TL'),
(220, 'Turkmenistan', 'TM'),
(221, 'Tunisia', 'TN'),
(222, 'Tonga', 'TO'),
(223, 'Turkey', 'TR'),
(224, 'Trinidad and Tobago', 'TT'),
(225, 'Tuvalu', 'TV'),
(226, 'Taiwan, Province of China', 'TW'),
(227, 'United Republic of Tanzania', 'TZ'),
(228, 'Ukraine', 'UA'),
(229, 'Uganda', 'UG'),
(230, 'United States', 'US'),
(231, 'Uruguay', 'UY'),
(232, 'Uzbekistan', 'UZ'),
(233, 'Holy See (Vatican City State)', 'VA'),
(234, 'Saint Vincent and the Grenadines', 'VC'),
(235, 'Venezuela', 'VE'),
(236, 'British Virgin Islands', 'VG'),
(237, 'US Virgin Islands', 'VI'),
(238, 'Vietnam', 'VN'),
(239, 'Vanuatu', 'VU'),
(240, 'Wallis and Futuna', 'WF'),
(241, 'Samoa', 'WS'),
(242, 'Kosovo', 'XK'),
(243, 'Yemen', 'YE'),
(244, 'Mayotte', 'YT'),
(245, 'South Africa', 'ZA'),
(246, 'Zambia', 'ZM'),
(247, 'Zimbabwe', 'ZW');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `country`
--
ALTER TABLE `country`
  ADD PRIMARY KEY (`id_country`) USING BTREE;

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `country`
--
ALTER TABLE `country`
  MODIFY `id_country` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=248;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
