const DEFAULTS_LIMIT = 10;
const DEFAULTS_PAGE = 1;
const DEFAULTS_TEXT_FILTER = null;
const DEFAULTS_SORT = null;

module.exports = {
  DEFAULTS_LIMIT,
  DEFAULTS_PAGE,
  DEFAULTS_TEXT_FILTER,
  DEFAULTS_SORT,
};
